from .student import StudentDeleteView
from .student import StudentUpdateView
from .student import StudentDetailView
from .student import StudentCreateView
from .student import StudentListView
from .user import UserDeleteView
from .user import UserUpdateView
from .user import UserDetailView
from .user import UserCreateView
from .user import UserListView
