from .issued_book import IssuedBookDeleteTestCase
from .issued_book import IssuedBookUpdateTestCase
from .issued_book import IssuedBookDetailTestCase
from .issued_book import IssuedBookCreateTestCase
from .issued_book import IssuedBookListTestCase
from .book import BookDeleteTestCase
from .book import BookUpdateTestCase
from .book import BookDetailTestCase
from .book import BookCreateTestCase
from .book import BookListTestCase
from .department import DepartmentDeleteTestCase
from .department import DepartmentUpdateTestCase
from .department import DepartmentDetailTestCase
from .department import DepartmentCreateTestCase
from .department import DepartmentListTestCase
