# Generated by Django 2.2.6 on 2022-04-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='user_accounts.Student', to_field='library_card_number'),
        ),
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Department'),
        ),
    ]
