# Generated by Django 2.2.6 on 2022-04-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220411_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
