from .issued_book_delete import IssuedBookDeleteView
from .issued_book_update import IssuedBookUpdateView
from .issued_book_detail import IssuedBookDetailView
from .issued_book_create import IssuedBookCreateView
from .issued_book_list import IssuedBookListView
