from .student import StudentDeleteTestCase
from .student import StudentUpdateTestCase
from .student import StudentDetailTestCase
from .student import StudentCreateTestCase
from .student import StudentListTestCase
from .user import UserDeleteTestCase
from .user import UserUpdateTestCase
from .user import UserDetailTestCase
from .user import UserCreateTestCase
from .user import UserListTestCase
