# Generated by Django 2.2.6 on 2022-04-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utype',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('LIBRARIAN', 'LIBRARIAN'), ('ADMINISTRATOR', 'ADMINISTRATOR')], default='LIBRARIAN', max_length=50, verbose_name='Type'),
        ),
    ]
