from .issued_book import IssuedBookDeleteView
from .issued_book import IssuedBookUpdateView
from .issued_book import IssuedBookDetailView
from .issued_book import IssuedBookCreateView
from .issued_book import IssuedBookListView
from .book import BookDeleteView
from .book import BookUpdateView
from .book import BookDetailView
from .book import BookCreateView
from .book import BookListView
from .department import DepartmentDeleteView
from .department import DepartmentUpdateView
from .department import DepartmentDetailView
from .department import DepartmentCreateView
from .department import DepartmentListView
